### ISSUE TITLE
Initial web page live on 1.9.2015

### ISSUE THREAD

**Issue by LockieMacpherson** [Irkka/dml-website#1]
content is to be added added to the structure, and then hosted live.

**Comment by Irkka** [comment]
Good, you started creating issues already! But, check out the Irkka/dml project Issue queue(or read facebook for rationale) for a style guide for future reference. I will move this issue to become a milestone rather than a separate task.

Issue structure guideline:

Heading/Title

Definition of Done:
<enter bullet points here>

Notes:
<if there is anything you wish to convey to the other person working on the issue, put it here in free form>
